# Examplary docker-compose file using the provided Dockerfile
version: '3.4'

services:
  example:
    privileged: true
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    devices:
        - /dev/i2c-1:/dev/i2c-1
        - /dev/gpiomem:/dev/gpiomem
        - /dev/mem:/dev/mem
        - /dev/spidev0.0:/dev/spidev0.0
        - /dev/spidev0.1:/dev/spidev0.1
    volumes:
        - /sys:/sys
